### PR TITLE
feat: Add ignore assets

### PR DESCRIPTION
**Pull request by hupe1980**
fixes: #5

```typescript
import * as path from 'path';
import { Stack } from '@aws-cdk/core';
import { Code, Function, Runtime } from '@aws-cdk/aws-lambda';

test('ignore assets', () => {
  const stack = new Stack();
  
  new Function(stack, 'Function', {
    code: Code.fromAsset(path.join(__dirname, 'fixtures', 'lambda')),
    runtime: Runtime.NODEJS_12_X,
    handler: 'index.handler'
  });

  expect(stack).toMatchCdkSnapshot({
    ignoreAssets: true,
  });
});

```

### CODE REVIEW

**Comment by moltar** [comment]
Amazing! Thanks!!

**Comment by henrist** [comment]
This looks great - many thanks!

One thing to notice is that this will also cause all other parameters to be excluded from the snapshot comparison.

We might consider supporting Lambda Function Versions as well. `lambda.Function.currentVersion` will produce unique logical ID that changes to produce updated versions, so it has to be handled somehow differently. I've solved this myself by rewriting the template, but this is for a full-application snapshot feature and not for unit testing (https://github.com/henrist/cdk-snapshot/blob/a9ba207301cb35d94e39725b512f22a3e11b1311/src/index.ts#L49-L59).

**Comment by hupe1980** [comment]
@henrist Right! We should definitely mention the exclusion of the parameters in the readme. And yes, something like ignoreCurrentVersionHashes definitely makes sense too.

**Comment by moltar** [comment]
Hm, I am still getting huge diffs:

```patch
 - Snapshot  - 64
    + Received  + 64

    @@ -17,25 +17,25 @@
                "type": "cdk:tree",
              },
              "messages": Array [],
            },
          ],
    -     "directory": "/var/folders/7v/v2jvmrwd3r94bw1vrg8r5nch0000gp/T/cdk.outkNsxaf",
    +     "directory": "/var/folders/7v/v2jvmrwd3r94bw1vrg8r5nch0000gp/T/cdk.outIcwwje",
          "manifest": Object {
            "artifacts": Object {
              "FooCore": Object {
                "environment": "aws://unknown-account/unknown-region",
                "metadata": Object {
                  "/FooCore": Array [
                    Object {
                      "data": Object {
    -                   "id": "bb34b71e4ecf5bbd97500b414ecd5d6a3868e8e4e4b591e627cf97af08ccd207",
    -                   "imageTag": "bb34b71e4ecf5bbd97500b414ecd5d6a3868e8e4e4b591e627cf97af08ccd207",
    +                   "id": "5530540c22fbdf6870ecd888be6309d4fab37ce5b64cac0d47c86bf6188881a7",
    +                   "imageTag": "5530540c22fbdf6870ecd888be6309d4fab37ce5b64cac0d47c86bf6188881a7",
                        "packaging": "container-image",
    -                   "path": "asset.bb34b71e4ecf5bbd97500b414ecd5d6a3868e8e4e4b591e627cf97af08ccd207",
    +                   "path": "asset.5530540c22fbdf6870ecd888be6309d4fab37ce5b64cac0d47c86bf6188881a7",
                        "repositoryName": "aws-cdk/assets",
    -                   "sourceHash": "bb34b71e4ecf5bbd97500b414ecd5d6a3868e8e4e4b591e627cf97af08ccd207",
    +                   "sourceHash": "5530540c22fbdf6870ecd888be6309d4fab37ce5b64cac0d47c86bf6188881a7",
```

**Pull request merged**
